# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ReRollBag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReRollBag
    pod 'GoogleMaps', '6.1.0'
    pod 'Google-Maps-iOS-Utils', '3.4.0'
  # Add the Firebase pod for Google Analytics
    pod 'FirebaseAnalytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
   pod 'FirebaseAuth'

  target 'ReRollBagTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReRollBagUITests' do
    # Pods for testing
  end
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
   end
   end
 end