# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ReRollBag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReRollBag
    pod 'GoogleMaps', '6.1.0'
    pod 'Google-Maps-iOS-Utils', '3.4.0'

  target 'ReRollBagTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReRollBagUITests' do
    # Pods for testing
  end

end
